# cargo-deny configuration file
# See: https://embarkstudios.github.io/cargo-deny/

[advisories]
# Configuration for the advisory checking
ignore = []

[licenses]
# Configuration for license checking
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]

[bans]
# Configuration for dependency banning
multiple-versions = "warn"

[sources]
# Configuration for source code checking
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]